// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type UploadFile struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	ObjectKey string
	CreatedAt time.Time
}

type UploadSession struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Purpose   string
	CreatedAt time.Time
	ExpiresAt time.Time
	MaxFiles  int32
}
