// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uploads.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUploadFile = `-- name: CreateUploadFile :one
INSERT INTO upload_files (
    id,
    session_id,
    object_key
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::text
)
RETURNING id, session_id, object_key, created_at
`

type CreateUploadFileParams struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	ObjectKey string
}

func (q *Queries) CreateUploadFile(ctx context.Context, arg CreateUploadFileParams) (UploadFile, error) {
	row := q.db.QueryRowContext(ctx, createUploadFile, arg.ID, arg.SessionID, arg.ObjectKey)
	var i UploadFile
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ObjectKey,
		&i.CreatedAt,
	)
	return i, err
}

const createUploadSession = `-- name: CreateUploadSession :one
INSERT INTO upload_sessions (
    id,
    owner_id,
    purpose,
    expires_at,
    max_files
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::timestamptz,
    $5::int
)
RETURNING id, owner_id, purpose, created_at, expires_at, max_files
`

type CreateUploadSessionParams struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Purpose   string
	ExpiresAt time.Time
	MaxFiles  int32
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, createUploadSession,
		arg.ID,
		arg.OwnerID,
		arg.Purpose,
		arg.ExpiresAt,
		arg.MaxFiles,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Purpose,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxFiles,
	)
	return i, err
}

const deleteUploadSession = `-- name: DeleteUploadSession :exec
DELETE FROM upload_sessions
WHERE id = $1::uuid
`

func (q *Queries) DeleteUploadSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUploadSession, id)
	return err
}

const getActiveUploadSessionByOwnerPurpose = `-- name: GetActiveUploadSessionByOwnerPurpose :one
SELECT id, owner_id, purpose, created_at, expires_at, max_files
FROM upload_sessions
WHERE owner_id = $1::uuid
AND purpose  = $2::text
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveUploadSessionByOwnerPurposeParams struct {
	OwnerID uuid.UUID
	Purpose string
}

func (q *Queries) GetActiveUploadSessionByOwnerPurpose(ctx context.Context, arg GetActiveUploadSessionByOwnerPurposeParams) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveUploadSessionByOwnerPurpose, arg.OwnerID, arg.Purpose)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Purpose,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxFiles,
	)
	return i, err
}

const getUploadFileByID = `-- name: GetUploadFileByID :one
SELECT id, session_id, object_key, created_at
FROM upload_files
WHERE id = $1::uuid
`

func (q *Queries) GetUploadFileByID(ctx context.Context, id uuid.UUID) (UploadFile, error) {
	row := q.db.QueryRowContext(ctx, getUploadFileByID, id)
	var i UploadFile
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ObjectKey,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadSessionByID = `-- name: GetUploadSessionByID :one
SELECT id, owner_id, purpose, created_at, expires_at, max_files
FROM upload_sessions
WHERE id = $1::uuid
`

func (q *Queries) GetUploadSessionByID(ctx context.Context, id uuid.UUID) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, getUploadSessionByID, id)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Purpose,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxFiles,
	)
	return i, err
}

const listUploadFilesBySession = `-- name: ListUploadFilesBySession :many
SELECT id, session_id, object_key, created_at
FROM upload_files
WHERE session_id = $1::uuid
ORDER BY created_at ASC
`

func (q *Queries) ListUploadFilesBySession(ctx context.Context, sessionID uuid.UUID) ([]UploadFile, error) {
	rows, err := q.db.QueryContext(ctx, listUploadFilesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadFile
	for rows.Next() {
		var i UploadFile
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ObjectKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
